//
//  PlanFocus.swift
//  Sub4
//
//  What kind of plan this is — patch 239.
//
//  THE PROBLEM THIS SOLVES
//  -----------------------
//  The week header printed "125 km all sports", which adds running kilometres
//  to cycling kilometres to swimming kilometres. Those are three different
//  quantities and their sum is not one. The line beneath it — "of which about
//  35 km is running" — was the honest correction, and it works because Sub-4 is
//  a running plan: there is one number worth leading with.
//
//  That hard-codes the assumption. A triathlon block has three numbers worth
//  leading with; a cycling block has one, and it is measured in hours rather
//  than kilometres. So the plan is asked what it is, rather than told.
//
//  DERIVED, NOT DECLARED
//  ---------------------
//  `plan.json` is generated by `extract_plan.py` from a source document, so a
//  `focus` field in `meta` would mean changing the extractor and would be wrong
//  the moment somebody edits the sessions without updating it. Counting the
//  sessions cannot go stale: a plan that becomes bike-heavy reads as bike-heavy
//  the next time it is loaded.
//
//  WHY SESSION COUNTS AND NOT TIME
//  -------------------------------
//  Time would be the better measure and is not available honestly. Run sessions
//  state distance, bike sessions state duration, swim sessions state metres —
//  converting them to a common unit needs an assumed pace, an assumed speed and
//  an assumed swim tempo, and the whole point of this file is to stop mixing
//  incommensurable quantities. A session count is crude, needs no assumption,
//  and answers the only question being asked: which sports is this plan mostly
//  made of.
//
//  THE 30% LINE
//  ------------
//  A threshold is a judgement, so it is named and stated rather than buried.
//  On this plan — three runs, one ride, one swim in a typical week — the shares
//  are 60/20/20 and only running leads, which is the behaviour that was there
//  before and that the athlete asked to keep. An even triathlon block is
//  33/33/33 and all three lead. A plan with a token weekly swim does not get to
//  call itself a swimming plan.
//
//  COMMITTED SESSIONS ONLY
//  -----------------------
//  The same three exclusions `plannedVolume` and `requiredSessionCount` apply:
//  not logged, dated, not optional. A block whose optional Zwift rides were
//  counted would drift towards calling itself a cycling plan on the strength of
//  sessions nobody committed to.
//

import Foundation

/// NOT `nonisolated`, and that is deliberate — patch 241.
///
/// It was, for one patch, copied from the habit of `Sub4Import`, whose
/// functions genuinely run off the main actor inside a database write. Nothing
/// here does: `derive` is called from `PlanStore.focus`, the week header and
/// the tests, all of which are main-actor. Marking it nonisolated only meant
/// `PlanStore.isOptional` — which is not — could no longer be called from it.
///
/// The rule this keeps tripping over is worth restating: `nonisolated` is not
/// a tidiness marker. It is a claim that the code can run anywhere, and it
/// obliges everything it touches to be able to as well.
struct PlanFocus: Equatable {

    /// The sports the plan is mostly made of, most first.
    let leads: [Discipline]

    /// Present in the plan, below the line. Most first.
    let supporting: [Discipline]

    /// Share of committed endurance sessions, per discipline.
    let shares: [Discipline: Double]

    /// True when more than one sport leads — a triathlon block rather than a
    /// running block with cross-training.
    var isMultisport: Bool { leads.count > 1 }

    /// A discipline that leads on its own, or nil when several do.
    var soleLead: Discipline? { leads.count == 1 ? leads[0] : nil }

    // MARK: Rules

    /// Named because it is a judgement. See the header.
    static let leadShare = 0.30

    /// Strength and rest are deliberately absent: they are support, not what a
    /// plan is *about*. A plan of three runs and three strength sessions is a
    /// running plan.
    static let endurance: [Discipline] = [.run, .bike, .swim]

    static func derive(sessions: [Session],
                       weeksByUid: [String: Week]) -> PlanFocus {
        let committed = sessions.filter { s in
            weeksByUid[s.weekUid]?.logged == false
                && s.date != nil
                && endurance.contains(s.discipline)
                && !PlanStore.isOptional(s)
        }
        guard !committed.isEmpty else {
            return PlanFocus(leads: [], supporting: [], shares: [:])
        }

        var counts: [Discipline: Int] = [:]
        for s in committed { counts[s.discipline, default: 0] += 1 }
        let total = Double(committed.count)

        var shares: [Discipline: Double] = [:]
        for d in endurance { shares[d] = Double(counts[d] ?? 0) / total }

        // Sorted by share, then by the fixed order in `endurance` so two sports
        // with an identical share come out the same way on every launch. A
        // dictionary has no order and `sorted` alone would not settle a tie.
        func order(_ ds: [Discipline]) -> [Discipline] {
            ds.sorted {
                let a = shares[$0] ?? 0, b = shares[$1] ?? 0
                if a != b { return a > b }
                return endurance.firstIndex(of: $0)! < endurance.firstIndex(of: $1)!
            }
        }

        let leads = order(endurance.filter { (shares[$0] ?? 0) >= leadShare })
        let supporting = order(endurance.filter {
            (shares[$0] ?? 0) > 0 && (shares[$0] ?? 0) < leadShare
        })
        return PlanFocus(leads: leads, supporting: supporting, shares: shares)
    }
}

// MARK: - Volume in each sport's own unit

extension PlanStore.PlanVolume {

    /// The figure for one discipline, in the unit that discipline is planned
    /// in, or nil when the week holds none of it.
    ///
    /// Running is planned in kilometres, riding in hours, swimming in metres.
    /// Returning a formatted string rather than a number is deliberate: there
    /// is no unit these three share, and anything that returned a bare Double
    /// would invite somebody to add them up again.
    func line(for discipline: Discipline) -> String? {
        switch discipline {
        case .run:
            guard runKm > 0 else { return nil }
            return String(format: "%@%.0f km running", runExact ? "" : "about ", runKm)
        case .bike:
            guard bikeHours > 0 else { return nil }
            let h = bikeHours
            return h == h.rounded()
                ? String(format: "%.0f h riding", h)
                : String(format: "%.1f h riding", h)
        case .swim:
            guard swimKm > 0 else { return nil }
            return swimKm < 1
                ? String(format: "%.0f m swimming", swimKm * 1000)
                : String(format: "%.1f km swimming", swimKm)
        case .strength:
            guard strengthSessions > 0 else { return nil }
            return "\(strengthSessions) strength"
        default:
            return nil
        }
    }
}

extension PlanStore {

    /// Derived once into `focusCache`, declared on the class in
    /// `PlanStore.swift`.
    ///
    /// `PlanStore.init` is private and reads the bundle, so there is exactly
    /// one store and no way to build another with a different plan. That is why
    /// `PlanFocus.derive` is static and takes its inputs: the rule can be
    /// tested against a run-heavy, a triathlon and a cycling plan without a
    /// store existing for any of them.
    var focus: PlanFocus {
        if let cached = focusCache { return cached }
        let f = PlanFocus.derive(sessions: plan.sessions, weeksByUid: weeksByUid)
        focusCache = f
        return f
    }

    /// `plannedVolume(throughDay:)` scoped to one week. Same three exclusions,
    /// stated once in `accumulate` so the two cannot drift.
    func plannedVolume(week: Week) -> PlanVolume {
        var v = PlanVolume()
        guard !week.logged else { return v }
        for s in sessions(inWeek: week) {
            guard s.date != nil, !Self.isOptional(s) else { continue }
            accumulate(s, into: &v)
        }
        return v
    }

    /// Every week's volume as the app computes it, one row per week — patch 240.
    ///
    /// WHY THIS EXISTS
    /// ---------------
    /// The week header shows two figures side by side that were produced by
    /// different code. "125 km all sports" comes from `plan.json`, whose stated
    /// totals were rewritten in patch 238 from a regex outside the app that
    /// counted optional sessions and double-counted "18 km, last 5 km @MP" as
    /// 23. "of which about 35 km running" comes from `plannedRunKm`, which
    /// handles both correctly. So the header disagreed with itself: 125 against
    /// a committed total nearer 95.
    ///
    /// The fix is not a better regex. It is to stop having two answers. This
    /// dumps what the app itself computes so those numbers can be written back
    /// into the file, after which the stated totals and the derived line are
    /// the same arithmetic and cannot drift.
    ///
    /// RAW COMPONENTS, NOT A TOTAL. A `km` figure needs a cycling speed, and
    /// that is a judgement that belongs in one place rather than being baked in
    /// here and then argued about later. `runExact` travels with the row
    /// because a week whose long run is written as "90 min" has a lower bound
    /// rather than a distance, and a total built from it should say so.
    var volumeExport: String {
        var lines = ["Sub4 plan volumes · patch \(AppVersion.patchLabel)",
                     "uid\tweekNo\tlogged\trunKm\trunExact\tbikeH\tswimKm\tstrength"]
        for w in plan.weeks {
            let v = plannedVolume(week: w)
            lines.append([w.uid,
                          w.weekNo.map(String.init) ?? "",
                          w.logged ? "1" : "0",
                          String(format: "%.2f", v.runKm),
                          v.runExact ? "1" : "0",
                          String(format: "%.3f", v.bikeHours),
                          String(format: "%.3f", v.swimKm),
                          String(v.strengthSessions)].joined(separator: "\t"))
        }
        // The stated figures alongside, so a diff needs no second paste.
        lines.append("")
        lines.append("stated in plan.json")
        lines.append("uid\tkm\th")
        for w in plan.weeks {
            let km = w.stats["km"].map { String(format: "%g", $0) } ?? ""
            let h = w.stats["h"].map { String(format: "%g", $0) } ?? ""
            lines.append("\(w.uid)\t\(km)\t\(h)")
        }
        return lines.joined(separator: "\n")
    }

    /// The headline for a week, in the sports this plan is about.
    ///
    /// One lead — "of which about 35 km is running", which is what a running
    /// plan wants and what was there before. Several — the sports side by side,
    /// with no "of which", because there is no single figure they are part of.
    func leadLine(for week: Week) -> String? {
        let v = plannedVolume(week: week)
        let parts = focus.leads.compactMap { v.line(for: $0) }
        guard !parts.isEmpty else { return nil }
        if focus.isMultisport { return parts.joined(separator: " · ") }
        return "of which \(parts[0])"
    }

    /// What the plan also contains, below the line. Strength is appended here
    /// rather than treated as a discipline — see `PlanFocus.endurance`.
    func supportingLine(for week: Week) -> String? {
        let v = plannedVolume(week: week)
        var parts = focus.supporting.compactMap { v.line(for: $0) }
        if let s = v.line(for: .strength) { parts.append(s) }
        guard !parts.isEmpty else { return nil }
        return "plus " + parts.joined(separator: " · ")
    }
}
